#!/bin/bash

grep -q firefox /home/vagrant/.bashrc ||
  cat >> /home/vagrant/.bashrc <<-EOF

  # git-prompt
  export GIT_PS1_SHOWDIRTYSTATE=true
  export GIT_PS1_SHOWCOLORHINTS=true
  export GIT_PS1_UNTRACKEDFILES=true
  export GIT_PS1_HIDE_IF_PWD_IGNORED=true

  # PS1 prepending the prior exit status:
  byobu_prompt_status() { local e=$?; [ $e != 0 ] && echo -e "$e "; }
  PS1='\[\e[38;5;202m\]$(byobu_prompt_status)\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
  export PROMPT_COMMAND="__git_ps1 '$PS1' ' '"

  firefox https://developer.download.nvidia.com/sdkmanager/redirects/sdkmanager-deb.html

  EOF
